name: Java CI with Gradle

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.PASSWORD_DB }}
          MYSQL_DATABASE: app
          MYSQL_USER: ${{ secrets.USER_DB }}
          MYSQL_PASSWORD: ${{ secrets.PASSWORD_DB }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Compose
        run: |
          docker-compose -f ./path_to_your_docker_compose_file/docker-compose.yml up -d
      - name: Waiting for container start
        run: sleep 30
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h"localhost" -P"3306" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
      - name: Run all tests (UI and DB)
        run: ./gradlew clean test \
          -DurlDB=${{ secrets.URL_DB }} \
          -DuserDB=${{ secrets.USER_DB }} \
          -DpasswordDB=${{ secrets.PASSWORD_DB }} \
          -Dselenide.headless=true
