name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
   
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      
      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew
      
      - name: Install dependencies (Docker, Chrome, JAVA_HOME 11)
        run: |
          echo "Installing Google Chrome..."
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Checking Google Chrome version..."
          google-chrome --version
          echo "Downloading compatible ChromeDriver..."
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          echo "Checking ChromeDriver version..."
          chromedriver --version

          sudo apt-get update
          sudo apt-get install -y docker-compose

          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
          
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Start Docker Compose services
        run: docker-compose up -d --build
   
      - name: Run application
        run: |
          echo "Starting application..."
          java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar &
          sleep 10 
          
      - name: Run tests
        run: ./gradlew clean test -DurlDB="jdbc:mysql://localhost:3306/app" --info

      - name: Generate and upload Allure report
        run: ./gradlew allureReport
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report

      - name: Stop services
        if: always()
        run: docker-compose down
