name: Java CI with Gradle

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conteiners start 
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yml 
      - name: Waiting for container start
        run: sleep 30 
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h"localhost" -P"3306" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
      - name: Run all tests (UI and DB)
        run: ./gradlew clean test \
          -DurlDB=${{ secrets.URL_DB }} \
          -DuserDB=${{ secrets.USER_DB }} \
          -DpasswordDB=${{ secrets.PASSWORD_DB }} \
          -Dselenide.headless=true
