name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Docker, Chrome, JDK 11)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io google-chrome-stable
          sudo systemctl start docker

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Start Docker Compose services
        run: docker-compose up -d --build

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Run application
        run: |
          echo "Starting application..."
          java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar &
          sleep 10 
          
      - name: Run tests
        run: ./gradlew clean test -DurlDB="jdbc:mysql://localhost:3306/app" --info

      - name: Generate and upload Allure report
        run: ./gradlew allureReport
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report

      - name: Stop services
        if: always()
        run: docker-compose down
