name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Install Google Chrome and ChromeDriver
        run: |
          echo "Installing Google Chrome..."
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Checking Google Chrome version..."
          google-chrome --version
          echo "Downloading compatible ChromeDriver..."
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          echo "Checking ChromeDriver version..."
          chromedriver --version
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Set JAVA_HOME to JDK 11
        run: |
          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Start Docker Compose services
        run: |
          docker-compose up -d --build
          
      - name: Wait for MySQL and other services to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          docker-compose exec -T mysql bash -c "until mysqladmin ping -h localhost --silent; do sleep 1; done;"
          
      - name: Run application
        run: |
          echo "Starting application..."
          java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar &
          sleep 10 
      - name: Run tests
        run: ./gradlew clean test -DurlDB="jdbc:mysql://localhost:3306/app" --info

      - name: Generate Allure report
        run: ./gradlew allureReport

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report

      - name: Stop services
        if: always()
        run: docker-compose down

      - name: Check Java version
        run: java -version
